version: '3'

services:
  postgres:
    image: postgres:10.4-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=rest_mock_db
      - POSTGRES_USER=rest_mock_user
      - POSTGRES_PASSWORD=rest_mock_password
      - PGDATA=/var/lib/postgresql/remote-data
    volumes:
      - './postgres-data:/var/lib/postgresql/remote-data'

  api:
    depends_on:
      - postgres
    image: 'rest-mock:backend'
    build:
      context: './src'
      dockerfile: './backend/Dockerfile'
    volumes:
      - ./src/backend:/app
    ports:
      - '3000:3000'
    command: npm run watch
    environment:
      - NODE_ENV=local
      - DB_HOST=postgres
      - DB_NAME=rest_mock_db
      - DB_USER=rest_mock_user
      - DB_PASS=rest_mock_password
      - DB_PORT=5432
